const motivationalQuotes = [
    { id: 1, quote: "Jediný způsob, jak dělat skvělou práci, je milovat to, co děláte.", author: "Steve Jobs", emoji: "💪" },
    { id: 2, quote: "Nejlepší způsob, jak předpovědět budoucnost, je vytvořit ji.", author: "Peter Drucker", emoji: "💡" },
    { id: 3, quote: "Míjíte 100 % šancí, které nevyužijete.", author: "Wayne Gretzky", emoji: "🏹" },
    { id: 4, quote: "Věř, že můžeš, a jsi na půli cesty.", author: "Theodore Roosevelt", emoji: "❤️" },
    { id: 5, quote: "Jediným limitem našich zítřejších úspěchů jsou pochybnosti dneška.", author: "Franklin D. Roosevelt", emoji: "🤔" },
    { id: 6, quote: "Cesta tisíce mil začíná jedním krokem.", author: "Lao Tzu", emoji: "🚶" },
    { id: 7, quote: "Úspěch není konečný, selhání není fatální: Je to odvaha pokračovat, která se počítá.", author: "Winston Churchill", emoji: "💪" },
    { id: 8, quote: "Těžkosti často připravují obyčejné lidi na mimořádný osud.", author: "C.S. Lewis", emoji: "⭐" },
    { id: 9, quote: "Máte v sobě právě teď vše, co potřebujete, abyste čelili čemukoliv, co vám svět může přinést.", author: "Brian Tracy", emoji: "🛡️" },
    { id: 10, quote: "Úspěch obvykle přichází k těm, kteří jsou příliš zaneprázdněni, než aby ho hledali.", author: "Henry David Thoreau", emoji: "🕰️" },
    { id: 11, quote: "Příležitosti se nestávají. Vytváříte je.", author: "Chris Grosser", emoji: "✨" },
    { id: 12, quote: "Nesledujte hodiny; dělejte to, co dělají. Pokračujte.", author: "Sam Levenson", emoji: "⏳" },
    { id: 13, quote: "Důvěřujte si a můžete dokázat cokoliv.", author: "David Goggins", emoji: "💪" },
    { id: 14, quote: "Každý den je nový začátek.", author: "T.S. Eliot", emoji: "🌅" },
    { id: 15, quote: "Můžeš dělat cokoliv, co si dokážeš představit, pokud se odvážíš začít.", author: "Earl Nightingale", emoji: "🚀" },
    { id: 16, quote: "Tvé největší boje přinášejí tvoje největší vítězství.", author: "Joyce Meyer", emoji: "🏆" },
    { id: 17, quote: "Jsi lepší než včera, ale ne tak dobrý jako zítra.", author: "Jesse Jackson", emoji: "📈" },
    { id: 18, quote: "Každý den je novou šancí změnit svůj život.", author: "Anonymous", emoji: "🔄" },
    { id: 19, quote: "Úspěch je suma malých snah, které se opakují den co den.", author: "Robert Collier", emoji: "📅" },
    { id: 20, quote: "Máš v sobě sílu změnit svůj život.", author: "Lailah Gifty Akita", emoji: "🔮" },
    { id: 21, quote: "Nezáleží na tom, jak pomalu jdeš, dokud se nezastavíš.", author: "Confucius", emoji: "🐢" },
    { id: 22, quote: "Změna začíná tím, že uděláš krok vpřed.", author: "Anonymous", emoji: "👣" },
    { id: 23, quote: "Cílem není být lepší než ostatní, ale být lepší, než jsi byl včera.", author: "Anonymous", emoji: "🌟" },
    { id: 24, quote: "Nic není nemožné. Slovo samo říká: 'Jsem možný.'", author: "Anonymous", emoji: "🚀" },
    { id: 25, quote: "Není důležité, jak pomalu jdeš, důležité je, že se nepřestáváš snažit.", author: "Confucius", emoji: "🏃" },
    { id: 26, quote: "Život je 10 % toho, co se ti stane, a 90 % toho, jak na to reaguješ.", author: "Charles R. Swindoll", emoji: "💬" },
    { id: 27, quote: "Věř, že to dokážeš, a půlka cesty je za tebou.", author: "Theodore Roosevelt", emoji: "🗺️" },
    { id: 28, quote: "Když se jedna dveře zavřou, jiná se otevřou.", author: "Alexander Graham Bell", emoji: "🚪" },
    { id: 29, quote: "Nezáleží na tom, jak často padneš, ale jak často se zvedneš.", author: "Anonymous", emoji: "💥" },
    { id: 30, quote: "Nečekej na příležitost. Vytvoř ji.", author: "Anonymous", emoji: "🛠️" },
    { id: 31, quote: "Největší riziko v životě je to, že se nikdy nedokážeš pokusit.", author: "Anonymous", emoji: "🎢" },
    { id: 32, quote: "Úspěch je schopnost přejít od jednoho neúspěchu k druhému, aniž byste ztratili nadšení.", author: "Winston Churchill", emoji: "🎯" },
    { id: 33, quote: "Chyby jsou důkazem, že se snažíte.", author: "Anonymous", emoji: "🔍" },
    { id: 34, quote: "Největší úspěch není nikdy skončit, ale nikdy se nevzdávat.", author: "Anonymous", emoji: "🏅" },
    { id: 35, quote: "Skvělé věci nikdy nevznikají z komfortní zóny.", author: "Anonymous", emoji: "🌍" },
    { id: 36, quote: "Nejlepším způsobem, jak se připravit na budoucnost, je ji vytvořit.", author: "Peter Drucker", emoji: "🔧" },
    { id: 37, quote: "Tvé činy dnes rozhodují o tvém zítřejším úspěchu.", author: "Anonymous", emoji: "🌟" },
    { id: 38, quote: "Sny se mohou stát skutečností, pokud se snažíte.", author: "Walt Disney", emoji: "🌠" },
    { id: 39, quote: "Důležitá není rychlost, ale směrem, kterým se ubíráte.", author: "Anonymous", emoji: "🧭" },
    { id: 40, quote: "Jediný limit tvého úspěchu je tvé odhodlání.", author: "Anonymous", emoji: "🚀" },
    { id: 41, quote: "Není nikdy pozdě začít znovu.", author: "Anonymous", emoji: "🌱" },
    { id: 42, quote: "Každý den je novou příležitostí být lepší.", author: "Anonymous", emoji: "🌞" },
    { id: 43, quote: "Změna začíná uvnitř.", author: "Anonymous", emoji: "🔄" },
    { id: 44, quote: "Největší úspěch přichází, když se vyrovnáte s neúspěchy.", author: "Anonymous", emoji: "🛠️" },
    { id: 45, quote: "Tvá síla je v tvém rozhodnutí.", author: "Anonymous", emoji: "💪" },
    { id: 46, quote: "Nejlepší čas na začátek bylo včera. Druhý nejlepší čas je dnes.", author: "Anonymous", emoji: "🕰️" },
    { id: 47, quote: "Každý nový začátek je příležitostí začít znovu lépe.", author: "Anonymous", emoji: "🌈" },
    { id: 48, quote: "Neexistují žádné tajemství úspěchu. Je to výsledek přípravy, tvrdé práce a učení z neúspěchů.", author: "Colin Powell", emoji: "📚" },
    { id: 49, quote: "Tvá budoucnost začíná dnes, ne zítra.", author: "Anonymous", emoji: "📅" },
    { id: 50, quote: "Každý den je novou šancí na změnu.", author: "Anonymous", emoji: "🔄" },
    { id: 51, quote: "Každý krok vpřed je krokem k úspěchu.", author: "Anonymous", emoji: "👣" },
    { id: 52, quote: "Věř v sebe a všechno je možné.", author: "Anonymous", emoji: "✨" },
    { id: 53, quote: "Někdy musíme vyhrát tím, že se nezdáme.", author: "Anonymous", emoji: "🏆" },
    { id: 54, quote: "Úspěch není o tom, co máš, ale o tom, co dokážeš.", author: "Anonymous", emoji: "🌟" },
    { id: 55, quote: "Sny se plní, když se o ně postaráme.", author: "Anonymous", emoji: "💫" },
    { id: 56, quote: "Můžete být čímkoliv, čím chcete být, pokud se rozhodnete bojovat.", author: "Anonymous", emoji: "⚔️" },
    { id: 57, quote: "Každý den se snaž být lepší, než jsi byl včera.", author: "Anonymous", emoji: "📈" },
    { id: 58, quote: "Tvá odvaha je klíčem k úspěchu.", author: "Anonymous", emoji: "🗝️" },
    { id: 59, quote: "Skvělá věc je, že vždy máš možnost začít znovu.", author: "Anonymous", emoji: "🔄" },
    { id: 60, quote: "Největší úspěch je, když se dokážeš zvednout po každém pádu.", author: "Anonymous", emoji: "💪" },
    { id: 61, quote: "Tvoje cesta začíná tím, že se rozhodneš jít dál.", author: "Anonymous", emoji: "🚶" },
    { id: 62, quote: "Nezáleží na tom, jak dlouho to trvá, ale na tom, že se nevzdáváš.", author: "Anonymous", emoji: "⏳" },
    { id: 63, quote: "Úspěch je schopnost přejít od neúspěchu k neúspěchu bez ztráty nadšení.", author: "Winston Churchill", emoji: "💪" },
    { id: 64, quote: "Důležité je ne to, co děláš, ale jak to děláš.", author: "Anonymous", emoji: "🔍" },
    { id: 65, quote: "Změna je životní konstantou. Nauč se jí přijmout.", author: "Anonymous", emoji: "🌟" },
    { id: 66, quote: "Každý den je novou šancí začít znovu.", author: "Anonymous", emoji: "🌅" },
    { id: 67, quote: "Snaž se být nejlepší verzí sebe sama.", author: "Anonymous", emoji: "✨" },
    { id: 68, quote: "Tvá vůle je tvým největším aktivem.", author: "Anonymous", emoji: "🏆" },
    { id: 69, quote: "Život je o tom, jak překonáš překážky, ne o tom, jak je obejdeš.", author: "Anonymous", emoji: "🏋️" },
    { id: 70, quote: "Když se jedna cesta uzavře, jiná se otevře.", author: "Anonymous", emoji: "🛤️" },
    { id: 71, quote: "Úspěch začíná rozhodnutím, že to zkusíš.", author: "Anonymous", emoji: "🚀" },
    { id: 72, quote: "Být skvělý neznamená být dokonalý. Znamená to snažit se vždy.", author: "Anonymous", emoji: "⭐" },
    { id: 73, quote: "V každém dni je něco, co tě může povzbudit.", author: "Anonymous", emoji: "☀️" },
    { id: 74, quote: "Věř, že můžeš, a jsi na půli cesty.", author: "Theodore Roosevelt", emoji: "💪" },
    { id: 75, quote: "Každý den je novou šancí začít znovu.", author: "Anonymous", emoji: "🌱" },
    { id: 76, quote: "Nezáleží na tom, jak daleko jsi, ale jak daleko jsi ochoten jít.", author: "Anonymous", emoji: "🏅" },
    { id: 77, quote: "Odvaha je nejen o tom, co děláme, ale i o tom, co se rozhodneme nedělat.", author: "Anonymous", emoji: "🛡️" },
    { id: 78, quote: "Úspěch je výsledkem přípravy, tvrdé práce a učení se z neúspěchů.", author: "Colin Powell", emoji: "📚" },
    { id: 79, quote: "Tvá budoucnost začíná dnes, ne zítra.", author: "Anonymous", emoji: "📅" },
    { id: 80, quote: "Každý den je novou šancí na změnu.", author: "Anonymous", emoji: "🔄" },
    { id: 81, quote: "Každý krok vpřed je krokem k úspěchu.", author: "Anonymous", emoji: "👣" },
    { id: 82, quote: "Věř v sebe a všechno je možné.", author: "Anonymous", emoji: "✨" },
    { id: 83, quote: "Někdy musíme vyhrát tím, že se nezdáme.", author: "Anonymous", emoji: "🏆" },
    { id: 84, quote: "Úspěch není o tom, co máš, ale o tom, co dokážeš.", author: "Anonymous", emoji: "🌟" },
    { id: 85, quote: "Sny se plní, když se o ně postaráme.", author: "Anonymous", emoji: "💫" },
    { id: 86, quote: "Můžete být čímkoliv, čím chcete být, pokud se rozhodnete bojovat.", author: "Anonymous", emoji: "⚔️" },
    { id: 87, quote: "Každý den se snaž být lepší, než jsi byl včera.", author: "Anonymous", emoji: "📈" },
    { id: 88, quote: "Tvá odvaha je klíčem k úspěchu.", author: "Anonymous", emoji: "🗝️" },
    { id: 89, quote: "Skvělá věc je, že vždy máš možnost začít znovu.", author: "Anonymous", emoji: "🔄" },
    { id: 90, quote: "Největší úspěch je, když se dokážeš zvednout po každém pádu.", author: "Anonymous", emoji: "💪" },
    { id: 91, quote: "Tvoje cesta začíná tím, že se rozhodneš jít dál.", author: "Anonymous", emoji: "🚶" },
    { id: 92, quote: "Nezáleží na tom, jak dlouho to trvá, ale na tom, že se nevzdáváš.", author: "Anonymous", emoji: "⏳" },
    { id: 93, quote: "Úspěch je schopnost přejít od neúspěchu k neúspěchu bez ztráty nadšení.", author: "Winston Churchill", emoji: "💪" },
    { id: 94, quote: "Důležité je ne to, co děláš, ale jak to děláš.", author: "Anonymous", emoji: "🔍" },
    { id: 95, quote: "Změna je životní konstantou. Nauč se jí přijmout.", author: "Anonymous", emoji: "🌟" },
    { id: 96, quote: "Každý den je novou šancí začít znovu.", author: "Anonymous", emoji: "🌅" },
    { id: 97, quote: "Snaž se být nejlepší verzí sebe sama.", author: "Anonymous", emoji: "✨" },
    { id: 98, quote: "Tvá vůle je tvým největším aktivem.", author: "Anonymous", emoji: "🏆" },
    { id: 99, quote: "Život je o tom, jak překonáš překážky, ne o tom, jak je obejdeš.", author: "Anonymous", emoji: "🏋️" },
    { id: 100, quote: "Když se jedna cesta uzavře, jiná se otevře.", author: "Anonymous", emoji: "🛤️" }
  ];

  export default motivationalQuotes;
  