const motivationalQuotes = [
  { id: 1, quote: "Jediný způsob, jak dělat skvělou práci, je milovat to, co děláte.", author: "Steve Jobs", emoji: "💪" },
  { id: 2, quote: "Nejlepší způsob, jak předpovědět budoucnost, je vytvořit ji.", author: "Peter Drucker", emoji: "💡" },
  { id: 3, quote: "Míjíte 100 % šancí, které nevyužijete.", author: "Wayne Gretzky", emoji: "🏹" },
  { id: 4, quote: "Věř, že můžeš, a jsi na půli cesty.", author: "Theodore Roosevelt", emoji: "❤️" },
  { id: 5, quote: "Jediným limitem našich zítřejších úspěchů jsou pochybnosti dneška.", author: "Franklin D. Roosevelt", emoji: "🤔" },
  { id: 6, quote: "Cesta tisíce mil začíná jedním krokem.", author: "Lao Tzu", emoji: "🚶" },
  { id: 7, quote: "Úspěch není konečný, selhání není fatální: Je to odvaha pokračovat, která se počítá.", author: "Winston Churchill", emoji: "💪" },
  { id: 8, quote: "Těžkosti často připravují obyčejné lidi na mimořádný osud.", author: "C.S. Lewis", emoji: "⭐" },
  { id: 9, quote: "Máte v sobě právě teď vše, co potřebujete, abyste čelili čemukoliv, co vám svět může přinést.", author: "Brian Tracy", emoji: "🛡️" },
  { id: 10, quote: "Úspěch obvykle přichází k těm, kteří jsou příliš zaneprázdněni, než aby ho hledali.", author: "Henry David Thoreau", emoji: "🕰️" },
  { id: 11, quote: "Příležitosti se nestávají. Vytváříte je.", author: "Chris Grosser", emoji: "✨" },
  { id: 12, quote: "Nesledujte hodiny; dělejte to, co dělají. Pokračujte.", author: "Sam Levenson", emoji: "⏳" },
  { id: 13, quote: "Důvěřujte si a můžete dokázat cokoliv.", author: "David Goggins", emoji: "💪" },
  { id: 14, quote: "Každý den je nový začátek.", author: "T.S. Eliot", emoji: "🌅" },
  { id: 15, quote: "Můžeš dělat cokoliv, co si dokážeš představit, pokud se odvážíš začít.", author: "Earl Nightingale", emoji: "🚀" },
  { id: 16, quote: "Tvé největší boje přinášejí tvoje největší vítězství.", author: "Joyce Meyer", emoji: "🏆" },
  { id: 17, quote: "Jsi lepší než včera, ale ne tak dobrý jako zítra.", author: "Jesse Jackson", emoji: "📈" },
  { id: 18, quote: "Každý den je novou šancí změnit svůj život.", author: "Sokrates", emoji: "🔄" },
  { id: 19, quote: "Úspěch je suma malých snah, které se opakují den co den.", author: "Robert Collier", emoji: "📅" },
  { id: 20, quote: "Máš v sobě sílu změnit svůj život.", author: "Lailah Gifty Akita", emoji: "🔮" },
  { id: 21, quote: "Nezáleží na tom, jak pomalu jdeš, dokud se nezastavíš.", author: "Confucius", emoji: "🐢" },
  { id: 22, quote: "Změna začíná tím, že uděláš krok vpřed.", author: "Epiktétos", emoji: "👣" },
  { id: 23, quote: "Cílem není být lepší než ostatní, ale být lepší, než jsi byl včera.", author: "Aristoteles", emoji: "🌟" },
  { id: 24, quote: "Nic není nemožné. Slovo samo říká: 'Jsem možný.'", author: "Sokrates", emoji: "🚀" },
  { id: 25, quote: "Není důležité, jak pomalu jdeš, důležité je, že se nepřestáváš snažit.", author: "Confucius", emoji: "🏃" },
  { id: 26, quote: "Život je 10 % toho, co se ti stane, a 90 % toho, jak na to reaguješ.", author: "Charles R. Swindoll", emoji: "💬" },
  { id: 27, quote: "Věř, že to dokážeš, a půlka cesty je za tebou.", author: "Theodore Roosevelt", emoji: "🗺️" },
  { id: 28, quote: "Když se jedna dveře zavřou, jiná se otevřou.", author: "Alexander Graham Bell", emoji: "🚪" },
  { id: 29, quote: "Nezáleží na tom, jak často padneš, ale jak často se zvedneš.", author: "Aristoteles", emoji: "💥" },
  { id: 30, quote: "Nečekej na příležitost. Vytvoř ji.", author: "Aristoteles", emoji: "🛠️" },
  { id: 31, quote: "Největší riziko v životě je to, že se nikdy nedokážeš pokusit.", author: "Epiktétos", emoji: "🎢" },
  { id: 32, quote: "Úspěch je schopnost přejít od jednoho neúspěchu k druhému, aniž byste ztratili nadšení.", author: "Winston Churchill", emoji: "🎯" },
  { id: 33, quote: "Chyby jsou důkazem, že se snažíte.", author: "Aristoteles", emoji: "🔍" },
  { id: 34, quote: "Největší úspěch není nikdy skončit, ale nikdy se nevzdávat.", author: "Epiktétos", emoji: "🏅" },
  { id: 35, quote: "Skvělé věci nikdy nevznikají z komfortní zóny.", author: "Aristoteles", emoji: "🌍" },
  { id: 36, quote: "Nejlepším způsobem, jak se připravit na budoucnost, je ji vytvořit.", author: "Peter Drucker", emoji: "🔧" },
  { id: 37, quote: "Tvé činy dnes rozhodují o tvém zítřejším úspěchu.", author: "Epiktétos", emoji: "🌟" },
  { id: 38, quote: "Sny se mohou stát skutečností, pokud se snažíte.", author: "Walt Disney", emoji: "🌠" },
  { id: 39, quote: "Důležitá není rychlost, ale směrem, kterým se ubíráte.", author: "Epiktétos", emoji: "🧭" },
  { id: 40, quote: "Jediný limit tvého úspěchu je tvé odhodlání.", author: "Epiktétos", emoji: "🚀" },
  { id: 41, quote: "Není nikdy pozdě začít znovu.", author: "Epiktétos", emoji: "🌱" },
  { id: 42, quote: "Každý den je novou příležitostí být lepší.", author: "Epiktétos", emoji: "🌞" },
  { id: 43, quote: "Změna začíná uvnitř.", author: "Aristoteles", emoji: "🔄" },
  { id: 44, quote: "Největší úspěch přichází, když se vyrovnáte s neúspěchy.", author: "Epiktétos", emoji: "🛠️" },
  { id: 45, quote: "Tvá síla je v tvém rozhodnutí.", author: "Epiktétos", emoji: "💪" },
  { id: 46, quote: "Nejlepší čas na začátek bylo včera. Druhý nejlepší čas je dnes.", author: "Epiktétos", emoji: "⏳" },
  { id: 47, quote: "Odvaha je vědět, co je třeba udělat, a i přesto to udělat.", author: "Aristoteles", emoji: "🦁" },
  { id: 48, quote: "Všechno, co potřebuješ, máš již v sobě.", author: "Sokrates", emoji: "🔮" },
  { id: 49, quote: "Vytrvalost je klíčem k úspěchu.", author: "Epiktétos", emoji: "🔑" },
  { id: 50, quote: "Nikdy se nevzdávej svých snů.", author: "Aristoteles", emoji: "✨" },
  { id: 51, quote: "Chcete-li dosáhnout velkých věcí, musíte být ochotni přijmout velké riziko.", author: "Aristoteles", emoji: "⚠️" },
    { id: 52, quote: "Život není o nalezení sebe sama, ale o vytvoření sebe sama.", author: "Sokrates", emoji: "🔧" },
    { id: 53, quote: "Nikdy neodkládejte to, co můžete udělat dnes, na zítřek.", author: "Epiktétos", emoji: "📅" },
    { id: 54, quote: "Úspěch je suma malých snah, které se opakují den co den.", author: "Epiktétos", emoji: "📆" },
    { id: 55, quote: "Věř v sebe a všechny ostatní v tobě začnou věřit.", author: "Aristoteles", emoji: "🔮" },
    { id: 56, quote: "Moc nemůžete změnit minulost, ale můžete změnit způsob, jak na ni reagujete.", author: "Sokrates", emoji: "🌟" },
    { id: 57, quote: "Každý krok, který uděláš, tě přibližuje k tvému cíli.", author: "Epiktétos", emoji: "👟" },
    { id: 58, quote: "Štěstí není v tom, co máte, ale v tom, co si myslíte, že máte.", author: "Aristoteles", emoji: "🍀" },
    { id: 59, quote: "Nepřestávejte se snažit, dokud nedosáhnete svého cíle.", author: "Sokrates", emoji: "🎯" },
    { id: 60, quote: "Vytrvalost a odhodlání jsou klíče k úspěchu.", author: "Epiktétos", emoji: "🔑" },
    { id: 61, quote: "Všechno, co je třeba k úspěchu, je rozhodnutí začít.", author: "Aristoteles", emoji: "⚡" },
    { id: 62, quote: "Mějte odvahu začít a víra v to, co můžete dosáhnout.", author: "Epiktétos", emoji: "🚀" },
    { id: 63, quote: "Na cestě k úspěchu nejsou žádné zkratky.", author: "Sokrates", emoji: "🛤️" },
    { id: 64, quote: "Úspěch není konečný, neúspěch není fatální; odvaha pokračovat je to, co se počítá.", author: "Aristoteles", emoji: "💫" },
    { id: 65, quote: "Překážky jsou ty věci, které vidíte, když ztratíte ze zřetele cíl.", author: "Sokrates", emoji: "🚧" },
    { id: 66, quote: "Důvěra v sebe sama je první tajemství úspěchu.", author: "Epiktétos", emoji: "🔒" },
    { id: 67, quote: "Neexistuje žádný neúspěch, pouze způsoby, které nefungují.", author: "Aristoteles", emoji: "🛠️" },
    { id: 68, quote: "Můžeš mít cokoli, co chceš, pokud se nebojíš pracovat tvrdě a dlouho.", author: "Sokrates", emoji: "💼" },
    { id: 69, quote: "Jediná věc, která stojí mezi vámi a vaším cílem, je vaše vlastní přesvědčení, že to nedokážete.", author: "Epiktétos", emoji: "🚧" },
    { id: 70, quote: "Skvělí lidé se nestávají velkými tím, že se nikdy nespletou, ale tím, že se nikdy nevzdávají.", author: "Aristoteles", emoji: "💪" },
    { id: 71, quote: "Připravte se na úspěch tím, že se poučíte z neúspěchu.", author: "Sokrates", emoji: "📚" },
    { id: 72, quote: "Změňte svůj způsob myšlení a změníte svůj svět.", author: "Epiktétos", emoji: "🌍" },
    { id: 73, quote: "Nebojte se neúspěchu; nebojte se nebýt pokusit se.", author: "Aristoteles", emoji: "🎢" },
    { id: 74, quote: "Vše, co potřebujete k úspěchu, je rozhodnutí být úspěšný.", author: "Sokrates", emoji: "📈" },
    { id: 75, quote: "Skvělé věci začínají tím, že se odvážíte snít.", author: "Epiktétos", emoji: "🌟" },
    { id: 76, quote: "Úspěch je výsledkem přípravy, tvrdé práce a učení se z neúspěchů.", author: "Aristoteles", emoji: "🛠️" },
    { id: 77, quote: "Každý den je novou šancí, aby se stal tvůj nejlepší den.", author: "Sokrates", emoji: "🌅" },
    { id: 78, quote: "Vždy se snažte být lepší než včera.", author: "Epiktétos", emoji: "⬆️" },
    { id: 79, quote: "Pokud se chcete stát úspěšnými, musíte začít myslet jako úspěšní lidé.", author: "Aristoteles", emoji: "🧠" },
    { id: 80, quote: "Nikdy nepochybujte o své schopnosti dosáhnout toho, co si přejete.", author: "Sokrates", emoji: "🎯" },
    { id: 81, quote: "Cesta k úspěchu je plná výzev, které vás formují.", author: "Epiktétos", emoji: "🛤️" },
    { id: 82, quote: "Skutečný úspěch spočívá v odhodlání pokračovat, i když čelíte neúspěchu.", author: "Aristoteles", emoji: "🔥" },
    { id: 83, quote: "Nezapomínejte, že každá překážka je příležitost k růstu.", author: "Sokrates", emoji: "🌱" },
    { id: 84, quote: "Váš úspěch je výsledkem vaší schopnosti učit se a přizpůsobit se.", author: "Epiktétos", emoji: "📚" },
    { id: 85, quote: "Důležité je nejen to, co děláte, ale i jak to děláte.", author: "Aristoteles", emoji: "🔍" },
    { id: 86, quote: "Úspěch je dlouhá cesta, která začíná malými kroky.", author: "Sokrates", emoji: "🪜" },
    { id: 87, quote: "Přijímejte výzvy jako příležitosti k růstu.", author: "Epiktétos", emoji: "🚀" },
    { id: 88, quote: "Nebojte se změn. Jsou to nové začátky.", author: "Aristoteles", emoji: "🔄" },
    { id: 89, quote: "Vytrvalost je cennější než rychlost.", author: "Sokrates", emoji: "🐢" },
    { id: 90, quote: "Změňte své myšlení a změníte svůj život.", author: "Epiktétos", emoji: "💭" },
    { id: 91, quote: "Skvělí lidé se neodrážejí od svých neúspěchů, ale od svého odhodlání uspět.", author: "Aristoteles", emoji: "🌟" },
    { id: 92, quote: "Přijměte změnu jako součást cesty k úspěchu.", author: "Sokrates", emoji: "🔄" },
    { id: 93, quote: "Vaše odhodlání a vytrvalost jsou vaší největší silou.", author: "Epiktétos", emoji: "🛡️" },
    { id: 94, quote: "Úspěch je sumou malých kroků, které děláte každý den.", author: "Aristoteles", emoji: "🗺️" },
    { id: 95, quote: "Vždy si pamatujte, že každá překážka je příležitost k učení.", author: "Sokrates", emoji: "📖" },
    { id: 96, quote: "Snažte se být nejlepší verzí sebe sama.", author: "Epiktétos", emoji: "🌟" },
    { id: 97, quote: "Skvělí lidé se odváží mít velké sny.", author: "Aristoteles", emoji: "🌠" },
    { id: 98, quote: "Vaše mysl je mocným nástrojem, pokud ji používáte správně.", author: "Sokrates", emoji: "🧠" },
    { id: 99, quote: "Úspěch je cesta, ne cíl.", author: "Epiktétos", emoji: "🛤️" },
    { id: 100, quote: "Odvaha je schopnost pokračovat navzdory strachu.", author: "Aristoteles", emoji: "🦁" },
    { id: 101, quote: "Nebuďte nečinní. Každá akce vás přiblíží k vašemu cíli.", author: "Aristoteles", emoji: "🏃‍♂️" },
    { id: 102, quote: "Sebeúcta a odhodlání jsou klíčem k úspěchu.", author: "Sokrates", emoji: "🔑" },
    { id: 103, quote: "Věřte si a budete překvapeni, co vše můžete dosáhnout.", author: "Epiktétos", emoji: "✨" },
    { id: 104, quote: "Úspěch začíná v mysli. Myslete pozitivně.", author: "Aristoteles", emoji: "💡" },
    { id: 105, quote: "Nikdy není pozdě na to, abyste se stali tím, čím chcete být.", author: "Sokrates", emoji: "⏳" },
    { id: 106, quote: "Vše, co potřebujete, je vůle a vytrvalost.", author: "Epiktétos", emoji: "💪" },
    { id: 107, quote: "Neúspěch není konec, ale začátek nového úsilí.", author: "Aristoteles", emoji: "🔄" },
    { id: 108, quote: "Přijměte výzvy jako příležitosti k růstu.", author: "Sokrates", emoji: "🎢" },
    { id: 109, quote: "Důležitá není pouze cílová čára, ale také cesta k ní.", author: "Epiktétos", emoji: "🏁" },
    { id: 110, quote: "Skutečná síla spočívá v pokračování, i když vše vypadá beznadějně.", author: "Aristoteles", emoji: "🔥" },
    { id: 111, quote: "Přijímejte změny jako příležitosti k růstu.", author: "Sokrates", emoji: "🔄" },
    { id: 112, quote: "Vaše činy jsou odrazem vašich myšlenek.", author: "Epiktétos", emoji: "💭" },
    { id: 113, quote: "Myslete pozitivně a pozitivní věci přijdou.", author: "Aristoteles", emoji: "🌞" },
    { id: 114, quote: "Buďte trpěliví. Vše se vyřeší v pravý čas.", author: "Sokrates", emoji: "⏳" },
    { id: 115, quote: "Odhodlání a vytrvalost vedou k úspěchu.", author: "Epiktétos", emoji: "🚀" },
    { id: 116, quote: "Úspěch je výsledkem tvrdé práce a odhodlání.", author: "Aristoteles", emoji: "🔨" },
    { id: 117, quote: "Nenechte se odradit překážkami na vaší cestě.", author: "Sokrates", emoji: "🛡️" },
    { id: 118, quote: "Cesta k úspěchu je dlouhá, ale každá cesta začíná prvním krokem.", author: "Epiktétos", emoji: "🗺️" },
    { id: 119, quote: "Nikdy se nevzdávejte svých snů.", author: "Aristoteles", emoji: "🌠" },
    { id: 120, quote: "Snažte se být lepší, než jste byli včera.", author: "Sokrates", emoji: "🔝" },
    { id: 121, quote: "Pokud nepracujete na svých cílech, nepracujete na sobě.", author: "Epiktétos", emoji: "🎯" },
    { id: 122, quote: "Přijímejte chyby jako příležitosti k učení.", author: "Aristoteles", emoji: "📚" },
    { id: 123, quote: "Úspěch není cílem, ale cestou, kterou kráčíte.", author: "Sokrates", emoji: "🛤️" },
    { id: 124, quote: "Věnujte se tomu, co vás činí šťastnými.", author: "Epiktétos", emoji: "😊" },
    { id: 125, quote: "Každý nový den přináší nové možnosti.", author: "Aristoteles", emoji: "🌅" },
    { id: 126, quote: "Myslete na své cíle, ne na překážky.", author: "Sokrates", emoji: "🔭" },
    { id: 127, quote: "Skvělí lidé jsou ti, kteří se nevzdávají, i když čelí neúspěchu.", author: "Epiktétos", emoji: "💪" },
    { id: 128, quote: "Odhodlání a vytrvalost jsou největšími spojenci úspěchu.", author: "Aristoteles", emoji: "⚔️" },
    { id: 129, quote: "Život je příležitost, využijte ji.", author: "Sokrates", emoji: "🌟" },
    { id: 130, quote: "Nenechte se odradit. Každý krok vás přiblíží k cíli.", author: "Epiktétos", emoji: "🚶‍♀️" },
    { id: 131, quote: "Důležitá není pouze rychlost, ale i směr, kterým jdete.", author: "Aristoteles", emoji: "🧭" },
    { id: 132, quote: "Jste tím, co děláte, ne tím, co říkáte, že uděláte.", author: "Sokrates", emoji: "🔨" },
    { id: 133, quote: "Úspěch je výsledkem odhodlání a tvrdé práce.", author: "Epiktétos", emoji: "🏆" },
    { id: 134, quote: "Snažte se každý den udělat něco, co vás přiblíží k vašim cílům.", author: "Aristoteles", emoji: "📈" },
    { id: 135, quote: "Nikdy nezapomínejte, proč jste začali.", author: "Sokrates", emoji: "❓" },
    { id: 136, quote: "Myslete velké a veliké věci se stanou.", author: "Epiktétos", emoji: "🏆" },
    { id: 137, quote: "Skvělí lidé vědí, že cesta k úspěchu je dlouhá, ale stojí za to.", author: "Aristoteles", emoji: "🚀" },
    { id: 138, quote: "Vaše myšlenky určují váš osud.", author: "Sokrates", emoji: "💭" },
    { id: 139, quote: "Přijímejte každou výzvu jako příležitost k růstu.", author: "Epiktétos", emoji: "🌱" },
    { id: 140, quote: "Úspěch je sumou vašich každodenních činů.", author: "Aristoteles", emoji: "🗓️" },
    { id: 141, quote: "Buďte ochotni se učit a růst.", author: "Sokrates", emoji: "📖" },
    { id: 142, quote: "Vytrvalost a odhodlání vedou k úspěchu.", author: "Epiktétos", emoji: "🔥" },
    { id: 143, quote: "Odhodlání a pozitivní přístup jsou klíčové k úspěchu.", author: "Aristoteles", emoji: "🗝️" },
    { id: 144, quote: "Skvělí lidé překonávají překážky s úsměvem.", author: "Sokrates", emoji: "😄" },
    { id: 145, quote: "Vaše akce jsou odrazem vašich myšlenek a snů.", author: "Epiktétos", emoji: "🌟" },
    { id: 146, quote: "Přijímejte nové výzvy jako příležitosti k růstu a učení.", author: "Aristoteles", emoji: "🚀" },
    { id: 147, quote: "Vždy se snažte být lepší, než jste byli včera.", author: "Sokrates", emoji: "📈" },
    { id: 148, quote: "Důležité je nejen kam směřujete, ale i jak se na cestě chováte.", author: "Epiktétos", emoji: "🛤️" },
    { id: 149, quote: "Úspěch není náhoda, je výsledkem tvrdé práce a odhodlání.", author: "Aristoteles", emoji: "🏆" },
    { id: 150, quote: "Přijímejte výzvy s otevřeným srdcem a myslí.", author: "Sokrates", emoji: "💓" },
    { id: 151, quote: "Každý krok k cíli je důležitý, bez ohledu na velikost.", author: "Epiktétos", emoji: "👣" },
    { id: 152, quote: "Myslete velké a nechte své sny stát se skutečností.", author: "Aristoteles", emoji: "🌌" },
    { id: 153, quote: "Vždy se snažte být nejlepší verzí sebe sama.", author: "Sokrates", emoji: "✨" },
    { id: 154, quote: "Úspěch je kombinací tvrdé práce, vytrvalosti a víry v sebe.", author: "Epiktétos", emoji: "🚀" },
    { id: 155, quote: "Přijímejte neúspěchy jako krok k úspěchu.", author: "Aristoteles", emoji: "🔄" },
    { id: 156, quote: "Buďte odvážní v každém kroku, který podniknete.", author: "Sokrates", emoji: "🦁" },
    { id: 157, quote: "Každý den je nová příležitost k dosažení vašich snů.", author: "Epiktétos", emoji: "🌅" },
    { id: 158, quote: "Snažte se být lepší, než jste byli včera.", author: "Aristoteles", emoji: "🔝" },
    { id: 159, quote: "Vaše síla spočívá v tom, jak čelíte překážkám.", author: "Sokrates", emoji: "🛡️" },
    { id: 160, quote: "Úspěch je součtem malých kroků, které děláte každý den.", author: "Epiktétos", emoji: "📏" },
    { id: 161, quote: "Buďte trpěliví a důslední ve svém úsilí.", author: "Aristoteles", emoji: "⏳" },
    { id: 162, quote: "Přijímejte výzvy s odhodláním a pozitivním přístupem.", author: "Sokrates", emoji: "🌟" },
    { id: 163, quote: "Úspěch je výsledkem neustálého úsilí a vytrvalosti.", author: "Epiktétos", emoji: "🔥" },
    { id: 164, quote: "Vaše mysl je vaším největším nástrojem k dosažení úspěchu.", author: "Aristoteles", emoji: "🧠" },
    { id: 165, quote: "Každý krok vpřed je krokem k vašim cílům.", author: "Sokrates", emoji: "🚶‍♂️" },
    { id: 166, quote: "Úspěch začíná v mysli a pokračuje tvrdou prací.", author: "Epiktétos", emoji: "🏋️" },
    { id: 167, quote: "Nikdy se nevzdávejte svých snů a cílů.", author: "Aristoteles", emoji: "🌠" },
    { id: 168, quote: "Odhodlání a pozitivní přístup jsou klíčem k úspěchu.", author: "Sokrates", emoji: "🗝️" },
    { id: 169, quote: "Buďte odvážní, protože odvaha otevírá nové možnosti.", author: "Epiktétos", emoji: "🦅" },
    { id: 170, quote: "Úspěch je výsledkem trpělivosti a tvrdé práce.", author: "Aristoteles", emoji: "🔨" },
    { id: 171, quote: "Přijímejte životní výzvy jako příležitosti k růstu.", author: "Sokrates", emoji: "📈" },
    { id: 172, quote: "Vždy hledejte nové cesty k dosažení svých cílů.", author: "Epiktétos", emoji: "🛤️" },
    { id: 173, quote: "Skvělí lidé nikdy nezapomínají na svůj cíl, i když čelí překážkám.", author: "Aristoteles", emoji: "🎯" },
    { id: 174, quote: "Vaše činy určují vaši budoucnost.", author: "Sokrates", emoji: "🔮" },
    { id: 175, quote: "Myslete pozitivně a nechte své sny stát se skutečností.", author: "Epiktétos", emoji: "💭" },
    { id: 176, quote: "Odvaha a vytrvalost vedou k úspěchu.", author: "Aristoteles", emoji: "🦁" },
    { id: 177, quote: "Snažte se každý den udělat něco, co vás přiblíží k vašim cílům.", author: "Sokrates", emoji: "🏃‍♀️" },
    { id: 178, quote: "Úspěch je výsledkem tvrdé práce a neustálého úsilí.", author: "Epiktétos", emoji: "🔨" },
    { id: 179, quote: "Buďte trpěliví a vytrvalí ve svém úsilí.", author: "Aristoteles", emoji: "⏳" },
    { id: 180, quote: "Přijímejte výzvy jako příležitosti k osobnímu růstu.", author: "Sokrates", emoji: "🌱" },
    { id: 181, quote: "Úspěch je kombinací tvrdé práce, odhodlání a pozitivního přístupu.", author: "Epiktétos", emoji: "🎉" },
    { id: 182, quote: "Každý den je novou příležitostí k dosažení vašich snů.", author: "Aristoteles", emoji: "🌅" },
    { id: 183, quote: "Vaše myšlenky a činy určují vaši budoucnost.", author: "Sokrates", emoji: "🧠" },
    { id: 184, quote: "Myslete velké, pracujte tvrdě a nechte své sny stát se skutečností.", author: "Epiktétos", emoji: "🌟" },
    { id: 185, quote: "Úspěch je součet malých kroků, které děláte každý den.", author: "Aristoteles", emoji: "📏" },
    { id: 186, quote: "Snažte se každý den udělat něco, co vás posune vpřed.", author: "Sokrates", emoji: "🏃‍♂️" },
    { id: 187, quote: "Odvaha a vytrvalost jsou klíčové k dosažení úspěchu.", author: "Epiktétos", emoji: "💪" },
    { id: 188, quote: "Skvělí lidé překonávají překážky s úsměvem a odhodláním.", author: "Aristoteles", emoji: "😁" },
    { id: 189, quote: "Úspěch je výsledkem neustálého úsilí a víry v sebe.", author: "Sokrates", emoji: "🚀" },
    { id: 190, quote: "Přijímejte každou překážku jako příležitost k učení a růstu.", author: "Epiktétos", emoji: "📚" },
    { id: 191, quote: "Vaše myšlenky mají moc vytvářet vaši realitu.", author: "Aristoteles", emoji: "🧠" },
    { id: 192, quote: "Každý krok vpřed je krokem k vašim cílům.", author: "Sokrates", emoji: "👣" },
    { id: 193, quote: "Úspěch je kombinací trpělivosti, odhodlání a tvrdé práce.", author: "Epiktétos", emoji: "🏆" },
    { id: 194, quote: "Snažte se být lepší každý den, ať už v malých nebo velkých věcech.", author: "Aristoteles", emoji: "📈" },
    { id: 195, quote: "Nikdy se nevzdávejte svých snů a cílů.", author: "Sokrates", emoji: "🌟" },
    { id: 196, quote: "Úspěch je výsledkem tvrdé práce, trpělivosti a odhodlání.", author: "Epiktétos", emoji: "💪" },
    { id: 197, quote: "Buďte odvážní a nevzdávejte se při prvním neúspěchu.", author: "Aristoteles", emoji: "🦁" },
    { id: 198, quote: "Vždy hledejte nové způsoby, jak se zlepšit a růst.", author: "Sokrates", emoji: "🔍" },
    { id: 199, quote: "Úspěch přichází k těm, kteří jsou ochotni se učit a růst.", author: "Epiktétos", emoji: "📚" },
    { id: 200, quote: "Každý nový den je novou příležitostí k dosažení vašich cílů.", author: "Aristoteles", emoji: "🌅" }
];
export default motivationalQuotes